// Minimal mock data powering the SRP demo.
export const INVENTORY = [
  {
    vin: "5J6TF3H33CL003984",
    year: 2012,
    make: "Honda",
    model: "Crosstour",
    trim: "EX-L",
    body: "hatchback",
    fuel: "gas",
    mileage: 110000,
    location: "SOUTH SAN FRANCISCO, CA",
    price: 10495,
    photos: [],
  },
  {
    vin: "JM3KFBCM3M0123456",
    year: 2021,
    make: "Mazda",
    model: "CX-5",
    trim: "Touring",
    body: "suv",
    fuel: "gas",
    mileage: 37820,
    location: "San Mateo, CA",
    price: 24995,
    photos: [],
  },
  {
    vin: "5YJYGAEE7LF012345",
    year: 2020,
    make: "Tesla",
    model: "Model Y",
    trim: "Long Range",
    body: "suv",
    fuel: "electric",
    mileage: 21500,
    location: "San Jose, CA",
    price: 32990,
    photos: [],
  },
];
